name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: true
          activate-environment: ""
      - uses: s-weigand/setup-conda@v1
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Post reports as comments in GitHub PRs
          nvidia-smi >> report.md
          conda install --file requirements.txt
          dvc repro
          git fetch prune
          cml-send-comment report.md
