name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v2
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
        run: |
          # Post reports as comments in GitHub PRs
          nvidia-smi >> report.md
          sudo apt-get update
          sudo apt install libasound2-dev python-dev python-numpy python-setuptools libsndfile-dev
          pip install -r requirements.txt
          sudo apt update
          dvc pull data
          dvc repro
          git fetch prune
          cml-send-comment report.md
