name: train-model

on:
  push:
    branches:
      - "train"

jobs:
  train:
    runs-on: [self-hosted, cml, gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}
      - name: cml_run
          
        run: |
          pip install -r requirements.txt
          dvc pull -aT data --run-cache
          git fetch prune
          dvc metrics diff --show-md staging > report.md
          cml-send-comment report.md
